### ISSUE TITLE
"Error: Spec Version not supported" on polkadot.js.org

### ISSUE THREAD

**Issue by DanielHirsbrunner** [Zondax/ledger-kusama#66]
Hello

I'm using the ledger app v 3.23.0 and polkadot.js Kusama version 2028 on windows 10 with chrome 88.0.4324.150.
When I try to send a transaction I get the error that the Spec Version is not supported (see below).

According to the Ledger App Manager i have the newest Version. I see here that there are a lot of newer Releases.
Is this problem related to the ledger app v. 3.23.0?
Is there a plan when a new release will be provided through the Ledger App Manager or do I need to install the developer release the manual way?

Thanks for your support
Daniel

Error:
signAndSend: error: Error: Spec version not supported
    at a (polkadot.02.b03594b7.js:1)
    at Ca.value (main.7e6e1c54.js:2)
    at /apps/async https:/polkadot.js.org/apps/main.7e6e1c54.js:2
    at async Ca.value (main.7e6e1c54.js:2)
    at async kce.signPayload (main.7e6e1c54.js:20)
    at async Object.value (polkadot.01.2e6c15bc.js:1)
    at async t.project (polkadot.01.2e6c15bc.js:1)

**Comment by dreamoftrees** [comment]
Getting the same issue. Please help my KSM is all locked away.

**Comment by jleni** [comment]
We are in contact with Ledger about this.
It should be fixed very soon (hopefully next few hours). 
We will keep this issue open for updates.

**Comment by kukabi** [comment]
Any news with this? And do you recommend installing from the repo if there'll be more delay?

**Comment by jeffbaz02** [comment]
I'm in the same boat - any update would be greatly appreciated.  Thank you.

**Comment by daniyarotegen** [comment]
I have the same error when unbonding staked funds

**Comment by abufarj919** [comment]
seen this too....

**Comment by feelwelltm** [comment]
2 problems with ledger Error: Spec version not supported. and the second error 1010 kusama in polkadot wallet I cant move the funds....for weeks,it is that legit,when you resolv the problems? when??? this is real money traped helloooooo

**Comment by feelwelltm** [comment]
We are in contact with Ledger about this.
It should be fixed very soon (hopefully next few hours).
We will keep this issue open for updates. 2 days passed !!!!!!!!!!!!!!!!! and 2 weeks for the error 1010 nothing happened do your job

**Comment by feelwelltm** [comment]
EVEN WITH THE UPDATE SAME ERROR IN LEDGER

**Comment by jleni** [comment]
Update:
This problem has been resolved. Ledger has just released v4.28.x
Please upgrade your Kusama app in Ledger Live

**Comment by feelwelltm** [comment]
i have tried to move the kusama again with your update still doesn't work
!!!!!!!!!! why???? really??? i repeat the kusama are in the polkadot adrees
and I cant move them.....you have made this update for my ledger and still
doesn't work

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

În vin., 12 feb. 2021 la 11:07, Juan Leni <notifications@github.com> a
scris:

**Comment by feelwelltm** [comment]
same 1010 error with the kusama update in ledger....

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

În vin., 12 feb. 2021 la 13:23, Feel Weel <feelwelltm@gmail.com> a scris:

**Comment by jleni** [comment]
> i have tried to move the kusama again with your update still doesn't work
!!!!!!!!!! why???? really??? i repeat the kusama are in the polkadot adrees
and I cant move them.....you have made this update for my ledger and still
doesn't work

This specific issue is related to the new release of kusama v28 that was not backward compatible. We have address the changes and Ledger has published the update.

If you sent KSM to your Polkadot pubkey/address by mistake, we are tracking those cases here:
https://github.com/Zondax/ledger-kusama/issues/56

As previously described, this is a very specific case (incorrectly sending coin to pubkeys in other chains) requires a recovery feature that is not standard and involves multiple stakeholders and a more complex process to get released.
It is very unfortunate for affected people. We have been asked to contribute with a recovery solution for this community issue and several people in our team (in addition to other stakeholders) are working on a tool to help everyone affected.

We will soon provide access to this tool, videos, tutorials, etc. but we must follow the right process.

**Comment by DanielHirsbrunner** [comment]
Hi @jleni 
My problem is solved, thanks a lot for your support

**Comment by feelwelltm** [comment]
I have reinstalled the new kusama version 4.28.2  on my nano ledger s.
I have the same 1010 error with my ledger when i want to transfer the
Kusama from the Polkadot wallet!  on the  https://polkadot.js.org/apps
i cant send the kusama anywhere!!!!! please help and make a version of
Kusama that works!!! I have ledger for security not for problems ok...be
serious

when the Kusama App - DOT recovery mode will be released for us, so we can
move the Kusama from Polkadot wallet...when??? there are real money blocked
in  https://polkadot.js.org

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

În vin., 12 feb. 2021 la 16:36, Daniel <notifications@github.com> a scris:

**Comment by abufarj919** [comment]
I have updated  new kusama version 4.28.2  and kusama app still will not stay open in ledger so in turn unable to sign transaction.     " Ledger error: App "kusama" does not seem to be open"

**Comment by jleni** [comment]
As explained here https://github.com/Zondax/ledger-kusama/issues/66#issuecomment-778172779 the last release was NOT about recovering KSM sent to Polkadot pubkeys.

> As previously described, this is a very specific case (incorrectly sending coin to pubkeys in other chains) requires a recovery feature that is not standard and involves multiple stakeholders and a more complex process to get released.
It is very unfortunate for affected people. We have been asked to contribute with a recovery solution for this community issue and several people in our team (in addition to other stakeholders) are working on a tool to help everyone affected.

We will soon provide access to this tool, videos, tutorials, etc. but we must follow the right process.
